routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'Auth\LoginController@showLoginForm');
Auth::routes(['register' => false]);

Route::group(['middleware'=>'isLoggedIn'], function() {
    Route::get('/dashboard', [
        'uses' => 'DashboardController@index',
        'as' => 'dashboard'
    ]);

    // route admin
    Route::group(['namespace'=>'Backend'], function() {
        Route::resource('place', 'PlaceController')->except(['destroy']);
        Route::get('/place/{id}/destroy', [
            'uses' => 'PlaceController@destroy',
            'as' => 'place.destroy'
        ]);

        Route::resource('user', 'UserController')->except(['destroy']);
        Route::get('/user/{id}/destroy', [
            'uses' => 'UserController@destroy',
            'as' => 'user.destroy'
        ]);

        Route::resource('satgas', 'SatgasController')->except(['destroy']);
        Route::get('/satgas/{id}/destroy', [
            'uses' => 'SatgasController@destroy',
            'as' => 'satgas.destroy'
        ]);

        Route::resource('vaccine', 'VaccineController')->except(['create', 'destroy', 'edit']);
        Route::get('/vaccine/{id}/create', [
            'uses' => 'VaccineController@create',
            'as' => 'vaccine.create'
        ]);
        Route::get('/vaccine/{uid}/{id}/edit', [
            'uses' => 'VaccineController@edit',
            'as' => 'vaccine.edit'
        ]);
        Route::get('/vaccine/{uid}/{id}/destroy', [
            'uses' => 'VaccineController@destroy',
            'as' => 'vaccine.destroy'
        ]);

        Route::resource('test-covid', 'TestCovidController')->except(['update', 'create', 'index', 'edit', 'destroy']);
        Route::group(['prefix'=>'test-covid','as'=>'test-covid.'], function() {
            Route::get('/test-covid/{uid}/index', [
                'uses' => 'TestCovidController@index',
                'as' => 'index'
            ]);
            Route::get('/test-covid/{uid}/create', [
                'uses' => 'TestCovidController@create',
                'as' => 'create'
            ]);
            Route::get('/test-covid/{uid}/{id}/edit', [
                'uses' => 'TestCovidController@edit',
                'as' => 'edit'
            ]);
            Route::put('/test-covid/{uid}/{id}/update', [
                'uses' => 'TestCovidController@update',
                'as' => 'update'
            ]);
            Route::get('/test-covid/{uid}/{id}/destroy', [
                'uses' => 'TestCovidController@destroy',
                'as' => 'destroy'
            ]);
        });

        Route::resource('user-journey', 'UserJourneyController');
        Route::group(['prefix' => 'user-journey', 'as' => 'user-journey.'], function() {
            Route::post('/get-journey', [
                'as' => 'get-journey',
                'uses' => 'UserJourneyController@getJourney'
            ]);
        });
        Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
    });

    // route satgas
    Route::group(['prefix' => 'dashboard-satgas', 'namespace'=>'Satgas', 'as' => 'satgas.'], function() {

        // test covid by satgas
        Route::get('/test-covid/datatable', [
            'as' => 'test-covid.datatable',
            'uses' => 'TestCovidController@datatable'
        ]);
        Route::get('/test-covid/{uid}/{id}/destroy', [
            'as' => 'test-covid.destroy',
            'uses' => 'TestCovidController@destroy'
        ]);
        Route::resource('test-covid', 'TestCovidController')->except(['show', 'edit', 'destroy']);

        Route::get('/vaccine/datatable', [
            'as' => 'vaccine.datatable',
            'uses' => 'VaccineController@datatable'
        ]);
        Route::get('/vaccine/{uid}/{id}/destroy', [
            'as' => 'vaccine.destroy',
            'uses' => 'VaccineController@destroy'
        ]);
        Route::resource('vaccine', 'VaccineController');
    });

    Route::get('get-user', [
        'as' => 'select.get-user',
        'uses' => 'SelectController@getUser'
    ]);
});

resources/views/admin/vaccine-cert/cert.blade.php
<html>
    <head>
        <style type='text/css'>
            body, html {
                margin: 0;
                padding: 0;
            }
            body {
                color: black;
                display: table;
                font-family: Georgia, serif;
                font-size: 24px;
                text-align: center;
            }
            .container {
                border: 20px solid tan;
                width: 750px;
                height: 563px;
                display: table-cell;
                vertical-align: middle;
            }
            .logo {
                color: tan;
            }

            .marquee {
                color: tan;
                font-size: 48px;
                margin: 20px;
            }
            .assignment {
                margin: 20px;
            }
            .person {
                border-bottom: 2px solid black;
                font-size: 32px;
                font-style: italic;
                margin: 20px auto;
                width: 400px;
            }
            .reason {
            	font-size:20px;
                margin: 20px;
            }
        </style>
    </head>
    <body>
        <div class="container">
            <div class="logo">
                Surat Keterangan Vaksinasi COVID-19
            </div>

            <div class="marquee">
                Sertifikat Vaksin
            </div>

            <div class="assignment">
                Sertifikat ini diberikan kepada
            </div>

            <div class="person">
                {{ $user['name'] }}
            </div>
            <div style="font-size:12px;">NIK : {{ $user['nik'] }} | ID : {{ $user['uid'] }}</div>
            <div style="font-size:15px;">telah dilakukan vaksinasi COVID-19 untuk dosis {{ $user['dosis'] }}</div>

            <div class="reason">
                Sesuai dengan Peraturan Menteri Kesehatan Republik Indonesia
            </div>
        </div>
    </body>
</html>

resources/views/admin/vaccine-cert/create.blade.php
@extends('layouts.template')

@section('userMenu', 'active')

@section('content')
<div class="main-panel">
    <nav class="navbar navbar-transparent navbar-absolute">
        <div class="container-fluid">
            <div class="navbar-minimize">
                <button id="minimizeSidebar" class="btn btn-round btn-white btn-fill btn-just-icon">
                    <i class="material-icons visible-on-sidebar-regular">more_vert</i>
                    <i class="material-icons visible-on-sidebar-mini">view_list</i>
                </button>
            </div>
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#"> Regular Forms </a>
            </div>
            <div class="collapse navbar-collapse">
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a href="#pablo" class="dropdown-toggle" data-toggle="dropdown">
                            <i class="material-icons">dashboard</i>
                            <p class="hidden-lg hidden-md">Dashboard</p>
                        </a>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            <i class="material-icons">notifications</i>
                            <span class="notification">5</span>
                            <p class="hidden-lg hidden-md">
                                Notifications
                                <b class="caret"></b>
                            </p>
                        </a>
                        <ul class="dropdown-menu">
                            <li>
                                <a href="#">Mike John responded to your email</a>
                            </li>
                            <li>
                                <a href="#">You have 5 new tasks</a>
                            </li>
                            <li>
                                <a href="#">You're now friend with Andrew</a>
                            </li>
                            <li>
                                <a href="#">Another Notification</a>
                            </li>
                            <li>
                                <a href="#">Another One</a>
                            </li>
                        </ul>
                    </li>
                    <li>
                        <a href="#pablo" class="dropdown-toggle" data-toggle="dropdown">
                            <i class="material-icons">person</i>
                            <p class="hidden-lg hidden-md">Profile</p>
                        </a>
                    </li>
                    <li class="separator hidden-lg hidden-md"></li>
                </ul>
                <form class="navbar-form navbar-right" role="search">
                    <div class="form-group form-search is-empty">
                        <input type="text" class="form-control" placeholder="Search">
                        <span class="material-input"></span>
                    </div>
                    <button type="submit" class="btn btn-white btn-round btn-just-icon">
                        <i class="material-icons">search</i>
                        <div class="ripple-container"></div>
                    </button>
                </form>
            </div>
        </div>
    </nav>
    <div class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        <form method="post" action="{{ route('vaccine.store') }}" class="form-horizontal">
                            @csrf
                            <input type="hidden" name="id" value="{{ $uid }}">
                            <div class="card-header card-header-text" data-background-color="rose">
                                <h4 class="card-title">Create Vaccine Cert</h4>
                            </div>
                            <div class="card-content">
                                <div class="row">
                                    <label class="col-sm-2 label-on-left">Title</label>
                                    <div class="col-sm-8">
                                        <div class="form-group label-floating is-empty">
                                            <label class="control-label"></label>
                                            <input type="text" class="form-control" placeholder="Name" name="title">
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <label class="col-sm-2 label-on-left">Vaccine Name</label>
                                    <div class="col-sm-8">
                                        <div class="form-group label-floating is-empty">
                                            <label class="control-label"></label>
                                            <input type="text" class="form-control" placeholder="Vaccine Name" name="vaccine_name">
                                        </div>
                                    </div>
                                </div>
                                <!-- <div class="row">
                                    <label class="col-sm-2 label-on-left">Status</label>
                                    <div class="col-sm-8">
                                        <div class="checkbox">
                                            <label>
                                                <input type="checkbox" name="status"> TRUE
                                            </label>
                                        </div>
                                    </div>
                                </div> -->
                                <button type="submit" class="btn btn-fill btn-rose">Submit</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/vaccine-cert/edit.blade.php
@extends('layouts.template')

@section('userMenu', 'active')

@section('content')
<div class="main-panel">
    <nav class="navbar navbar-transparent navbar-absolute">
        <div class="container-fluid">
            <div class="navbar-minimize">
                <button id="minimizeSidebar" class="btn btn-round btn-white btn-fill btn-just-icon">
                    <i class="material-icons visible-on-sidebar-regular">more_vert</i>
                    <i class="material-icons visible-on-sidebar-mini">view_list</i>
                </button>
            </div>
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#"> Regular Forms </a>
            </div>
            <div class="collapse navbar-collapse">
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a href="#pablo" class="dropdown-toggle" data-toggle="dropdown">
                            <i class="material-icons">dashboard</i>
                            <p class="hidden-lg hidden-md">Dashboard</p>
                        </a>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            <i class="material-icons">notifications</i>
                            <span class="notification">5</span>
                            <p class="hidden-lg hidden-md">
                                Notifications
                                <b class="caret"></b>
                            </p>
                        </a>
                        <ul class="dropdown-menu">
                            <li>
                                <a href="#">Mike John responded to your email</a>
                            </li>
                            <li>
                                <a href="#">You have 5 new tasks</a>
                            </li>
                            <li>
                                <a href="#">You're now friend with Andrew</a>
                            </li>
                            <li>
                                <a href="#">Another Notification</a>
                            </li>
                            <li>
                                <a href="#">Another One</a>
                            </li>
                        </ul>
                    </li>
                    <li>
                        <a href="#pablo" class="dropdown-toggle" data-toggle="dropdown">
                            <i class="material-icons">person</i>
                            <p class="hidden-lg hidden-md">Profile</p>
                        </a>
                    </li>
                    <li class="separator hidden-lg hidden-md"></li>
                </ul>
                <form class="navbar-form navbar-right" role="search">
                    <div class="form-group form-search is-empty">
                        <input type="text" class="form-control" placeholder="Search">
                        <span class="material-input"></span>
                    </div>
                    <button type="submit" class="btn btn-white btn-round btn-just-icon">
                        <i class="material-icons">search</i>
                        <div class="ripple-container"></div>
                    </button>
                </form>
            </div>
        </div>
    </nav>
    <div class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        <form method="post" action="{{ route('vaccine.update', $id) }}" class="form-horizontal">
                            @csrf
                            @method('PUT')
                            <input type="hidden" name="uid" value="{{ $uid }}">

                            <div class="card-header card-header-text" data-background-color="rose">
                                <h4 class="card-title">Create Vaccine Cert</h4>
                            </div>
                            <div class="card-content">
                                <div class="row">
                                    <label class="col-sm-2 label-on-left">Title</label>
                                    <div class="col-sm-8">
                                        <div class="form-group label-floating is-empty">
                                            <label class="control-label"></label>
                                            <input type="text" class="form-control" placeholder="Title" name="title" value="{{ $item['title'] }}">
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <label class="col-sm-2 label-on-left">Vaccine Name</label>
                                    <div class="col-sm-8">
                                        <div class="form-group label-floating is-empty">
                                            <label class="control-label"></label>
                                            <input type="text" class="form-control" placeholder="Vaccine Name" name="vaccine_name" value="{{ $item['vaccine_name'] }}">
                                        </div>
                                    </div>
                                </div>
                                <!-- <div class="row">
                                    <label class="col-sm-2 label-on-left">Status</label>
                                    <div class="col-sm-8">
                                        <div class="checkbox">
                                            <label>
                                                <input type="checkbox" name="status"> TRUE
                                            </label>
                                        </div>
                                    </div>
                                </div> -->
                                <button type="submit" class="btn btn-fill btn-rose">Submit</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/vaccine-cert/index.blade.php
@extends('layouts.template')

@section('userMenu', 'active')

@section('content')
<div class="main-panel">
    <nav class="navbar navbar-transparent navbar-absolute">
        <div class="container-fluid">
            <div class="navbar-minimize">
                <button id="minimizeSidebar" class="btn btn-round btn-white btn-fill btn-just-icon">
                    <i class="material-icons visible-on-sidebar-regular">more_vert</i>
                    <i class="material-icons visible-on-sidebar-mini">view_list</i>
                </button>
            </div>
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#"> List Users </a>
            </div>
            <div class="collapse navbar-collapse">
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a href="#pablo" class="dropdown-toggle" data-toggle="dropdown">
                            <i class="material-icons">dashboard</i>
                            <p class="hidden-lg hidden-md">Dashboard</p>
                        </a>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            <i class="material-icons">notifications</i>
                            <span class="notification">5</span>
                            <p class="hidden-lg hidden-md">
                                Notifications
                                <b class="caret"></b>
                            </p>
                        </a>
                        <ul class="dropdown-menu">
                            <li>
                                <a href="#">Mike John responded to your email</a>
                            </li>
                            <li>
                                <a href="#">You have 5 new tasks</a>
                            </li>
                            <li>
                                <a href="#">You're now friend with Andrew</a>
                            </li>
                            <li>
                                <a href="#">Another Notification</a>
                            </li>
                            <li>
                                <a href="#">Another One</a>
                            </li>
                        </ul>
                    </li>
                    <li>
                        <a href="#pablo" class="dropdown-toggle" data-toggle="dropdown">
                            <i class="material-icons">person</i>
                            <p class="hidden-lg hidden-md">Profile</p>
                        </a>
                    </li>
                    <li class="separator hidden-lg hidden-md"></li>
                </ul>
                <form class="navbar-form navbar-right" role="search">
                    <div class="form-group form-search is-empty">
                        <input type="text" class="form-control" placeholder="Search">
                        <span class="material-input"></span>
                    </div>
                    <button type="submit" class="btn btn-white btn-round btn-just-icon">
                        <i class="material-icons">search</i>
                        <div class="ripple-container"></div>
                    </button>
                </form>
            </div>
        </div>
    </nav>
    <div class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-header card-header-icon" data-background-color="purple">
                            <a href="{{ route('vaccine.create', $uid) }}"><i class="fa fa-plus"></i></a>
                        </div>
                        <div class="card-content">
                            <h4 class="card-title">List Vaccine</h4>
                            <div class="toolbar">
                                <!--        Here you can write extra buttons/actions for the toolbar              -->
                            </div>
                            <div class="material-datatables">
                                <table class="datatables table table-striped table-no-bordered table-hover" cellspacing="0" width="100%" style="width:100%">
                                    <thead>
                                        <tr>
                                            <th>No</th>
                                            <th>Tmage</th>
                                            <th>Title</th>
                                            <th>Vaccine Name</th>
                                            <th class="disabled-sorting text-right">Actions</th>
                                        </tr>
                                    </thead>
                                    <tfoot>
                                        <tr>
                                            <th>No</th>
                                            <th>Tmage</th>
                                            <th>Title</th>
                                            <th>Vaccine Name</th>
                                            <th class="disabled-sorting text-right">Actions</th>
                                        </tr>
                                    </tfoot>
                                    <tbody>
                                        @forelse ($vaccines as $v)
                                        <tr>
                                            <td>{{ $loop->iteration }}</td>
                                            <td><img src="{{ $v['image'] }}" style="width:100px;"></td>
                                            <td>{{ $v['title'] }}</td>
                                            <td>{{ $v['vaccine_name'] }}</td>
                                            <td class="disabled-sorting text-right">
                                                <a href="{{ route('vaccine.edit', ['id' => $v['id'], 'uid' => $uid]) }}" type="button" rel="tooltip" class="btn btn-sm btn-info btn-round">
                                                    <i class="material-icons">edit</i>
                                                </a>
                                                <a onclick="return confirm('Are you sure you want to delete this item?');" href="{{ route('vaccine.destroy', ['id' => $v['id'], 'uid' => $uid]) }}" rel="tooltip" class="btn btn-sm btn-danger btn-round">
                                                    <i class="material-icons">close</i>
                                                </a>
                                            </td>
                                        </tr>
                                        @empty
                                        @endforelse
                                    </tbody>
                                </table>
                            </div>
                        </div>
                        <!-- end content-->
                    </div>
                    <!--  end card  -->
                </div>
                <!-- end col-md-12 -->
            </div>
            <!-- end row -->
        </div>
    </div>
    <!-- modal -->
    <div class="modal fade" id="modalVac" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLongTitle">Form Vaccine Cert</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <form method="#" action="#" id="form_vaccine_cert">
                    @csrf
                    <div class="modal-body">
                        <div class="form-group label-floating is-empty">
                            <label class="control-label">Vaccine Name</label>
                            <input type="text" class="form-control" name="vaccine_name" id="vaccine_name">
                            <span class="material-input"></span>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-primary" id="btn_save">Save changes</button>
                </form>
            </div>
        </div>
    </div>
</div>
</div>
@endsection

@section('script')
<script></script>
@endsection