routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'Auth\LoginController@showLoginForm');
Auth::routes(['register' => false]);

Route::group(['middleware'=>'isLoggedIn'], function() {
    Route::get('/dashboard', [
        'uses' => 'DashboardController@index',
        'as' => 'dashboard'
    ]);

    // route admin
    Route::group(['namespace'=>'Backend'], function() {
        Route::resource('place', 'PlaceController')->except(['destroy']);
        Route::get('/place/{id}/destroy', [
            'uses' => 'PlaceController@destroy',
            'as' => 'place.destroy'
        ]);

        Route::resource('user', 'UserController')->except(['destroy']);
        Route::get('/user/{id}/destroy', [
            'uses' => 'UserController@destroy',
            'as' => 'user.destroy'
        ]);

        Route::resource('satgas', 'SatgasController')->except(['destroy']);
        Route::get('/satgas/{id}/destroy', [
            'uses' => 'SatgasController@destroy',
            'as' => 'satgas.destroy'
        ]);

        Route::resource('vaccine', 'VaccineController')->except(['create', 'destroy', 'edit']);
        Route::get('/vaccine/{id}/create', [
            'uses' => 'VaccineController@create',
            'as' => 'vaccine.create'
        ]);
        Route::get('/vaccine/{uid}/{id}/edit', [
            'uses' => 'VaccineController@edit',
            'as' => 'vaccine.edit'
        ]);
        Route::get('/vaccine/{uid}/{id}/destroy', [
            'uses' => 'VaccineController@destroy',
            'as' => 'vaccine.destroy'
        ]);

        Route::resource('test-covid', 'TestCovidController')->except(['update', 'create', 'index', 'edit', 'destroy']);
        Route::group(['prefix'=>'test-covid','as'=>'test-covid.'], function() {
            Route::get('/test-covid/{uid}/index', [
                'uses' => 'TestCovidController@index',
                'as' => 'index'
            ]);
            Route::get('/test-covid/{uid}/create', [
                'uses' => 'TestCovidController@create',
                'as' => 'create'
            ]);
            Route::get('/test-covid/{uid}/{id}/edit', [
                'uses' => 'TestCovidController@edit',
                'as' => 'edit'
            ]);
            Route::put('/test-covid/{uid}/{id}/update', [
                'uses' => 'TestCovidController@update',
                'as' => 'update'
            ]);
            Route::get('/test-covid/{uid}/{id}/destroy', [
                'uses' => 'TestCovidController@destroy',
                'as' => 'destroy'
            ]);
        });

        Route::resource('user-journey', 'UserJourneyController');
        Route::group(['prefix' => 'user-journey', 'as' => 'user-journey.'], function() {
            Route::post('/get-journey', [
                'as' => 'get-journey',
                'uses' => 'UserJourneyController@getJourney'
            ]);
        });
        Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
    });

    // route satgas
    Route::group(['prefix' => 'dashboard-satgas', 'namespace'=>'Satgas', 'as' => 'satgas.'], function() {

        // test covid by satgas
        Route::get('/test-covid/datatable', [
            'as' => 'test-covid.datatable',
            'uses' => 'TestCovidController@datatable'
        ]);
        Route::get('/test-covid/{uid}/{id}/destroy', [
            'as' => 'test-covid.destroy',
            'uses' => 'TestCovidController@destroy'
        ]);
        Route::resource('test-covid', 'TestCovidController')->except(['show', 'edit', 'destroy']);

        Route::get('/vaccine/datatable', [
            'as' => 'vaccine.datatable',
            'uses' => 'VaccineController@datatable'
        ]);
        Route::get('/vaccine/{uid}/{id}/destroy', [
            'as' => 'vaccine.destroy',
            'uses' => 'VaccineController@destroy'
        ]);
        Route::resource('vaccine', 'VaccineController');
    });

    Route::get('get-user', [
        'as' => 'select.get-user',
        'uses' => 'SelectController@getUser'
    ]);
});

app/Http/Controllers/Backend/PlaceController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Kreait\Firebase\Database;
use RealRashid\SweetAlert\Facades\Alert;

class PlaceController extends Controller
{
    public function __construct(Database $database) 
    {
        $this->database = $database;
        $this->tbName = 'Places';
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        if (!empty(session('error_msg')))
            Alert::error('Gagal !', session('error_msg'));
        if (!empty(session('success')))
            Alert::success('Success !', session('success'));

        $ref = $this->database->getReference($this->tbName)->getValue();
        $data['places'] = $ref;
        return view('admin.places.index', $data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.places.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $ref = $this->database->getReference($this->tbName)->getValue();
        $lastId = str_replace("places", "", collect($ref)->sortDesc()->values()->all()[0]['id']);
        $id = "places" . ($lastId + 1);
        $postData = [
            'banner' => '', 
            'id' => $id, 
            'lat' => (int)$request->lat, 
            'long' => (int)$request->long, 
            'name' => $request->name, 
            'need_test' => strtolower($request->test), 
            'need_vaccine' => (int)$request->need_vaccine, 
            'quota' => (int)$request->quota, 
        ];

        $postRef = $this->database->getReference($this->tbName)->getChild($id)->set($postData);

        if ($postRef) {
            return redirect()->route('place.index')->withSuccess('Success add item !');
        }

        return redirect()->route('place.index')->with('error_msg', 'Failed add item !');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $data['id'] = $id;
        return view('admin.places.show', $data);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $ref = $this->database->getReference("{$this->tbName}/{$id}")
           ->getValue();
        // dd($ref);
        $data['item'] = $ref;
        return view('admin.places.edit', $data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $postData = [
            'banner' => '', 
            'id' => $id, 
            'lat' => (float)$request->lat, 
            'long' => (float)$request->long, 
            'name' => $request->name, 
            'need_test' => strtolower($request->test), 
            'need_vaccine' => (int)$request->need_vaccine, 
            'quota' => (int)$request->quota, 
        ];

        $postRef = $this->database->getReference($this->tbName)->getChild($id)->update($postData);

        if ($postRef) {
            return redirect()->route('place.index')->withSuccess('Success update item !');
        }

        return redirect()->route('place.index')->with('error_msg', 'Failed update item !');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $postRef = $this->database->getReference($this->tbName)->getChild($id)->remove();
        if ($postRef) {
            return redirect()->route('place.index')->withSuccess('Success delete item !');
        }

        return redirect()->route('place.index')->with('error_msg', 'Failed delete item !');
    }
}

resources/views/admin/places/create.blade.php
@extends('layouts.template')

@section('placeMenu', 'active')

@section('content')
<div class="main-panel">
    <nav class="navbar navbar-transparent navbar-absolute">
        <div class="container-fluid">
            <div class="navbar-minimize">
                <button id="minimizeSidebar" class="btn btn-round btn-white btn-fill btn-just-icon">
                    <i class="material-icons visible-on-sidebar-regular">more_vert</i>
                    <i class="material-icons visible-on-sidebar-mini">view_list</i>
                </button>
            </div>
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#"> Regular Forms </a>
            </div>
            <div class="collapse navbar-collapse">
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a href="#pablo" class="dropdown-toggle" data-toggle="dropdown">
                            <i class="material-icons">dashboard</i>
                            <p class="hidden-lg hidden-md">Dashboard</p>
                        </a>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            <i class="material-icons">notifications</i>
                            <span class="notification">5</span>
                            <p class="hidden-lg hidden-md">
                                Notifications
                                <b class="caret"></b>
                            </p>
                        </a>
                        <ul class="dropdown-menu">
                            <li>
                                <a href="#">Mike John responded to your email</a>
                            </li>
                            <li>
                                <a href="#">You have 5 new tasks</a>
                            </li>
                            <li>
                                <a href="#">You're now friend with Andrew</a>
                            </li>
                            <li>
                                <a href="#">Another Notification</a>
                            </li>
                            <li>
                                <a href="#">Another One</a>
                            </li>
                        </ul>
                    </li>
                    <li>
                        <a href="#pablo" class="dropdown-toggle" data-toggle="dropdown">
                            <i class="material-icons">person</i>
                            <p class="hidden-lg hidden-md">Profile</p>
                        </a>
                    </li>
                    <li class="separator hidden-lg hidden-md"></li>
                </ul>
                <form class="navbar-form navbar-right" role="search">
                    <div class="form-group form-search is-empty">
                        <input type="text" class="form-control" placeholder="Search">
                        <span class="material-input"></span>
                    </div>
                    <button type="submit" class="btn btn-white btn-round btn-just-icon">
                        <i class="material-icons">search</i>
                        <div class="ripple-container"></div>
                    </button>
                </form>
            </div>
        </div>
    </nav>
    <div class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        <form method="post" action="{{ route('place.store') }}" class="form-horizontal">
                            @csrf
                            <div class="card-header card-header-text" data-background-color="rose">
                                <h4 class="card-title">Create Place</h4>
                            </div>
                            <div class="card-content">
                                <div class="row">
                                    <label class="col-sm-2 label-on-left">Name</label>
                                    <div class="col-sm-8">
                                        <div class="form-group label-floating is-empty">
                                            <label class="control-label"></label>
                                            <input type="text" class="form-control" placeholder="Name" name="name">
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <label class="col-sm-2 label-on-left">Lat</label>
                                    <div class="col-sm-8">
                                        <div class="form-group label-floating is-empty">
                                            <label class="control-label"></label>
                                            <input type="text" class="form-control" placeholder="Lat" name="lat">
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <label class="col-sm-2 label-on-left">Long</label>
                                    <div class="col-sm-8">
                                        <div class="form-group label-floating is-empty">
                                            <label class="control-label"></label>
                                            <input type="text" class="form-control" placeholder="Long" name="long">
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <label class="col-sm-2 label-on-left">Test</label>
                                    <div class="col-sm-4">
                                        <div class="form-group label-floating is-empty">
                                            <label class="control-label"></label>
                                            <select name="test" class="selectpicker" data-style="btn btn-primary btn-round" title="Single Select" data-size="7">
                                                <option disabled selected>Choose Test</option>
                                                <option value="">TIDAK PERLU</option>
                                                <option value="pcr">PCR</option>
                                                <option value="swab">SWAB</option>
                                            </select>
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <label class="col-sm-2 label-on-left">Quota</label>
                                    <div class="col-sm-8">
                                        <div class="form-group label-floating is-empty">
                                            <label class="control-label"></label>
                                            <input type="number" placeholder="Quota" class="form-control" name="quota">
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <label class="col-sm-2 label-on-left">Need Vaccine</label>
                                    <div class="col-sm-4">
                                        <div class="form-group label-floating is-empty">
                                            <label class="control-label"></label>
                                            <select name="need_vaccine" class="selectpicker" data-style="btn btn-primary btn-round" title="Single Select" data-size="7">
                                                <option disabled selected>Choose Test</option>
                                                <option value="0">0</option>
                                                <option value="1">1</option>
                                                <option value="2">2</option>
                                            </select>
                                        </div>
                                    </div>
                                </div>
                                <button type="submit" class="btn btn-fill btn-rose">Submit</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/places/index.blade.php
@extends('layouts.template')

@section('placeMenu', 'active')

@section('content')
<div class="main-panel">
    <nav class="navbar navbar-transparent navbar-absolute">
        <div class="container-fluid">
            <div class="navbar-minimize">
                <button id="minimizeSidebar" class="btn btn-round btn-white btn-fill btn-just-icon">
                    <i class="material-icons visible-on-sidebar-regular">more_vert</i>
                    <i class="material-icons visible-on-sidebar-mini">view_list</i>
                </button>
            </div>
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#"> List Places </a>
            </div>
            <div class="collapse navbar-collapse">
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a href="#pablo" class="dropdown-toggle" data-toggle="dropdown">
                            <i class="material-icons">dashboard</i>
                            <p class="hidden-lg hidden-md">Dashboard</p>
                        </a>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            <i class="material-icons">notifications</i>
                            <span class="notification">5</span>
                            <p class="hidden-lg hidden-md">
                                Notifications
                                <b class="caret"></b>
                            </p>
                        </a>
                        <ul class="dropdown-menu">
                            <li>
                                <a href="#">Mike John responded to your email</a>
                            </li>
                            <li>
                                <a href="#">You have 5 new tasks</a>
                            </li>
                            <li>
                                <a href="#">You're now friend with Andrew</a>
                            </li>
                            <li>
                                <a href="#">Another Notification</a>
                            </li>
                            <li>
                                <a href="#">Another One</a>
                            </li>
                        </ul>
                    </li>
                    <li>
                        <a href="#pablo" class="dropdown-toggle" data-toggle="dropdown">
                            <i class="material-icons">person</i>
                            <p class="hidden-lg hidden-md">Profile</p>
                        </a>
                    </li>
                    <li class="separator hidden-lg hidden-md"></li>
                </ul>
                <form class="navbar-form navbar-right" role="search">
                    <div class="form-group form-search is-empty">
                        <input type="text" class="form-control" placeholder="Search">
                        <span class="material-input"></span>
                    </div>
                    <button type="submit" class="btn btn-white btn-round btn-just-icon">
                        <i class="material-icons">search</i>
                        <div class="ripple-container"></div>
                    </button>
                </form>
            </div>
        </div>
    </nav>
    <div class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        <a href="{{ route('place.create') }}">
                            <div class="card-header card-header-icon" data-background-color="purple">
                                <i class="material-icons">add</i>
                            </div>
                        </a>
                        <div class="card-content">
                            <h4 class="card-title">List Places</h4>
                            <div class="toolbar">
                                <!--        Here you can write extra buttons/actions for the toolbar              -->
                            </div>
                            <div class="material-datatables">
                                <table class="datatables table table-striped table-no-bordered table-hover" cellspacing="0" width="100%" style="width:100%">
                                    <thead>
                                        <tr>
                                            <th>Nama</th>
                                            <th>Lat</th>
                                            <th>Long</th>
                                            <th>Kuota</th>
                                            <th class="disabled-sorting text-right">Actions</th>
                                        </tr>
                                    </thead>
                                    <tfoot>
                                        <tr>
                                            <th>Nama</th>
                                            <th>Lat</th>
                                            <th>Long</th>
                                            <th>Kuota</th>
                                            <th class="disabled-sorting text-right">Actions</th>
                                        </tr>
                                    </tfoot>
                                    <tbody>
                                        @forelse ($places as $place)
                                            <tr>
                                                <td>{{ $place['name'] }}</td>
                                                <td>{{ $place['lat'] }}</td>
                                                <td>{{ $place['long'] ?? "" }}</td>
                                                <td>{{ $place['quota'] }}</td>
                                                <td class="td-actions text-right">
                                                    <a href="{{ route('place.show', $place['id'] ?? "") }}" type="button" rel="tooltip" class="btn btn-sm btn-success btn-round">
                                                        <i class="fa fa-eye"></i>
                                                    </a>
                                                    <a href="{{ route('place.edit', $place['id'] ?? "") }}" type="button" rel="tooltip" class="btn btn-sm btn-info btn-round">
                                                        <i class="material-icons">edit</i>
                                                    </a>
                                                    <a onclick="return confirm('Are you sure you want to delete this item?');" href="{{ route('place.destroy', $place['id']) }}" rel="tooltip" class="btn btn-sm btn-danger btn-round">
                                                        <i class="material-icons">close</i>
                                                    </a>
                                                </td>
                                            </tr>
                                        @empty
                                        @endforelse
                                    </tbody>
                                </table>
                            </div>
                        </div>
                        <!-- end content-->
                    </div>
                    <!--  end card  -->
                </div>
                <!-- end col-md-12 -->
            </div>
            <!-- end row -->
        </div>
    </div>
</div>
@endsection

resources/views/admin/places/show.blade.php
@extends('layouts.template')

@section('placeMenu', 'active')

@section('content')
<div class="main-panel">
    <nav class="navbar navbar-transparent navbar-absolute">
        <div class="container-fluid">
            <div class="navbar-minimize">
                <button id="minimizeSidebar" class="btn btn-round btn-white btn-fill btn-just-icon">
                    <i class="material-icons visible-on-sidebar-regular">more_vert</i>
                    <i class="material-icons visible-on-sidebar-mini">view_list</i>
                </button>
            </div>
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#"> Regular Forms </a>
            </div>
            <div class="collapse navbar-collapse">
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a href="#pablo" class="dropdown-toggle" data-toggle="dropdown">
                            <i class="material-icons">dashboard</i>
                            <p class="hidden-lg hidden-md">Dashboard</p>
                        </a>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            <i class="material-icons">notifications</i>
                            <span class="notification">5</span>
                            <p class="hidden-lg hidden-md">
                                Notifications
                                <b class="caret"></b>
                            </p>
                        </a>
                        <ul class="dropdown-menu">
                            <li>
                                <a href="#">Mike John responded to your email</a>
                            </li>
                            <li>
                                <a href="#">You have 5 new tasks</a>
                            </li>
                            <li>
                                <a href="#">You're now friend with Andrew</a>
                            </li>
                            <li>
                                <a href="#">Another Notification</a>
                            </li>
                            <li>
                                <a href="#">Another One</a>
                            </li>
                        </ul>
                    </li>
                    <li>
                        <a href="#pablo" class="dropdown-toggle" data-toggle="dropdown">
                            <i class="material-icons">person</i>
                            <p class="hidden-lg hidden-md">Profile</p>
                        </a>
                    </li>
                    <li class="separator hidden-lg hidden-md"></li>
                </ul>
                <form class="navbar-form navbar-right" role="search">
                    <div class="form-group form-search is-empty">
                        <input type="text" class="form-control" placeholder="Search">
                        <span class="material-input"></span>
                    </div>
                    <button type="submit" class="btn btn-white btn-round btn-just-icon">
                        <i class="material-icons">search</i>
                        <div class="ripple-container"></div>
                    </button>
                </form>
            </div>
        </div>
    </nav>
    <div class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        <form method="post" class="form-horizontal">
                            <div class="card-header card-header-text" data-background-color="rose">
                                <h4 class="card-title">QRCode Place</h4>
                            </div>
                            <div class="card-content">
                                <center>
                                <h1>Scan here !</h1>
                                <br>
                                <div class="row">
                                    {!! QrCode::size(250)->generate($id); !!}
                                </div>
                                </center>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection