routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'Auth\LoginController@showLoginForm');
Auth::routes(['register' => false]);

Route::group(['middleware'=>'isLoggedIn'], function() {
    Route::get('/dashboard', [
        'uses' => 'DashboardController@index',
        'as' => 'dashboard'
    ]);

    // route admin
    Route::group(['namespace'=>'Backend'], function() {
        Route::resource('place', 'PlaceController')->except(['destroy']);
        Route::get('/place/{id}/destroy', [
            'uses' => 'PlaceController@destroy',
            'as' => 'place.destroy'
        ]);

        Route::resource('user', 'UserController')->except(['destroy']);
        Route::get('/user/{id}/destroy', [
            'uses' => 'UserController@destroy',
            'as' => 'user.destroy'
        ]);

        Route::resource('satgas', 'SatgasController')->except(['destroy']);
        Route::get('/satgas/{id}/destroy', [
            'uses' => 'SatgasController@destroy',
            'as' => 'satgas.destroy'
        ]);

        Route::resource('vaccine', 'VaccineController')->except(['create', 'destroy', 'edit']);
        Route::get('/vaccine/{id}/create', [
            'uses' => 'VaccineController@create',
            'as' => 'vaccine.create'
        ]);
        Route::get('/vaccine/{uid}/{id}/edit', [
            'uses' => 'VaccineController@edit',
            'as' => 'vaccine.edit'
        ]);
        Route::get('/vaccine/{uid}/{id}/destroy', [
            'uses' => 'VaccineController@destroy',
            'as' => 'vaccine.destroy'
        ]);

        Route::resource('test-covid', 'TestCovidController')->except(['update', 'create', 'index', 'edit', 'destroy']);
        Route::group(['prefix'=>'test-covid','as'=>'test-covid.'], function() {
            Route::get('/test-covid/{uid}/index', [
                'uses' => 'TestCovidController@index',
                'as' => 'index'
            ]);
            Route::get('/test-covid/{uid}/create', [
                'uses' => 'TestCovidController@create',
                'as' => 'create'
            ]);
            Route::get('/test-covid/{uid}/{id}/edit', [
                'uses' => 'TestCovidController@edit',
                'as' => 'edit'
            ]);
            Route::put('/test-covid/{uid}/{id}/update', [
                'uses' => 'TestCovidController@update',
                'as' => 'update'
            ]);
            Route::get('/test-covid/{uid}/{id}/destroy', [
                'uses' => 'TestCovidController@destroy',
                'as' => 'destroy'
            ]);
        });

        Route::resource('user-journey', 'UserJourneyController');
        Route::group(['prefix' => 'user-journey', 'as' => 'user-journey.'], function() {
            Route::post('/get-journey', [
                'as' => 'get-journey',
                'uses' => 'UserJourneyController@getJourney'
            ]);
        });
        Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
    });

    // route satgas
    Route::group(['prefix' => 'dashboard-satgas', 'namespace'=>'Satgas', 'as' => 'satgas.'], function() {

        // test covid by satgas
        Route::get('/test-covid/datatable', [
            'as' => 'test-covid.datatable',
            'uses' => 'TestCovidController@datatable'
        ]);
        Route::get('/test-covid/{uid}/{id}/destroy', [
            'as' => 'test-covid.destroy',
            'uses' => 'TestCovidController@destroy'
        ]);
        Route::resource('test-covid', 'TestCovidController')->except(['show', 'edit', 'destroy']);

        Route::get('/vaccine/datatable', [
            'as' => 'vaccine.datatable',
            'uses' => 'VaccineController@datatable'
        ]);
        Route::get('/vaccine/{uid}/{id}/destroy', [
            'as' => 'vaccine.destroy',
            'uses' => 'VaccineController@destroy'
        ]);
        Route::resource('vaccine', 'VaccineController');
    });

    Route::get('get-user', [
        'as' => 'select.get-user',
        'uses' => 'SelectController@getUser'
    ]);
});

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function scopeRole($q, $v)
    {
        return $q->where('id_role', $v);
    }
}

app/Http/Controllers/Backend/UserController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Kreait\Firebase\Database;
use RealRashid\SweetAlert\Facades\Alert;

class UserController extends Controller
{
    public function __construct(Database $database) 
    {
        $this->database = $database;
        $this->tbUser = 'Users';
        $this->tbVaccine = 'VaccineCert';
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        if (!empty(session('error_msg')))
            Alert::error('Gagal !', session('error_msg'));
        if (!empty(session('success')))
            Alert::success('Success !', session('success'));

        $ref = $this->database->getReference($this->tbUser)->getValue();
        $data['users'] = $ref;
        return view('admin.users.index', $data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.users.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $ref = $this->database->getReference($this->tbUser)->getValue();
        
        $postUser = [
            // 'uid' => 
            'nik' => $request->nik,
            'name' => $request->name,
            'email' => $request->email,
            'password' => $request->password,
            'phoneNumber' => $request->phoneNumber,
            'gender' => empty($request->gender) ? 0 : $request->gender
        ];

        $postRef = $this->database->getReference($this->tbUser)->push($postUser)->getKey();
        $postUser['uid'] = $postRef;
        $updateRef = $this->database->getReference($this->tbUser)->getChild($postRef)->update($postUser);

        $postVaccine = [
            'vaccinecert1' => [
                'id' => 'vaccinecert1',
                'image' => '',
                'seq' => 1,
                'status' => false,
                'title' => 'Vaksin Pertama',
                "vaccine_name" => ""
            ],
            'vaccinecert2' => [
                'id' => 'vaccinecert2',
                'image' => '',
                'seq' => 2,
                'status' => false,
                'title' => 'Vaksin Kedua',
                "vaccine_name" => ""
            ],
        ];

        $postVaccines = $this->database->getReference($this->tbVaccine."/".$postRef)->set($postVaccine)->getKey();

        if ($postVaccines) {
            return redirect()->route('user.index')->withSuccess('Success add item !');
        }

        return redirect()->route('user.index')->with('error_msg', 'Failed add item !');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $ref = $this->database->getReference("{$this->tbUser}/{$id}")
           ->getValue();

        $data['item'] = $ref;
        $data['uid'] = $id;
        return view('admin.users.edit', $data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $postData = [
            // 'uid' => 
            'nik' => $request->nik,
            'name' => $request->name,
            'email' => $request->email,
            'phoneNumber' => $request->phoneNumber,
            'gender' => empty($request->gender) ? 0 : $request->gender
        ];
        
        if (!empty($request->password))
            $postData['password'] = $request->password;

        $postRef = $this->database->getReference($this->tbUser)->getChild($id)->update($postData);

        if ($postRef) {
            return redirect()->route('user.index')->withSuccess('Success update item !');
        }

        return redirect()->route('user.index')->with('error_msg', 'Failed update item !');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/admin/users/create.blade.php
@extends('layouts.template')

@section('userMenu', 'active')

@section('content')
<div class="main-panel">
    <nav class="navbar navbar-transparent navbar-absolute">
        <div class="container-fluid">
            <div class="navbar-minimize">
                <button id="minimizeSidebar" class="btn btn-round btn-white btn-fill btn-just-icon">
                    <i class="material-icons visible-on-sidebar-regular">more_vert</i>
                    <i class="material-icons visible-on-sidebar-mini">view_list</i>
                </button>
            </div>
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#"> Regular Forms </a>
            </div>
            <div class="collapse navbar-collapse">
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a href="#pablo" class="dropdown-toggle" data-toggle="dropdown">
                            <i class="material-icons">dashboard</i>
                            <p class="hidden-lg hidden-md">Dashboard</p>
                        </a>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            <i class="material-icons">notifications</i>
                            <span class="notification">5</span>
                            <p class="hidden-lg hidden-md">
                                Notifications
                                <b class="caret"></b>
                            </p>
                        </a>
                        <ul class="dropdown-menu">
                            <li>
                                <a href="#">Mike John responded to your email</a>
                            </li>
                            <li>
                                <a href="#">You have 5 new tasks</a>
                            </li>
                            <li>
                                <a href="#">You're now friend with Andrew</a>
                            </li>
                            <li>
                                <a href="#">Another Notification</a>
                            </li>
                            <li>
                                <a href="#">Another One</a>
                            </li>
                        </ul>
                    </li>
                    <li>
                        <a href="#pablo" class="dropdown-toggle" data-toggle="dropdown">
                            <i class="material-icons">person</i>
                            <p class="hidden-lg hidden-md">Profile</p>
                        </a>
                    </li>
                    <li class="separator hidden-lg hidden-md"></li>
                </ul>
                <form class="navbar-form navbar-right" role="search">
                    <div class="form-group form-search is-empty">
                        <input type="text" class="form-control" placeholder="Search">
                        <span class="material-input"></span>
                    </div>
                    <button type="submit" class="btn btn-white btn-round btn-just-icon">
                        <i class="material-icons">search</i>
                        <div class="ripple-container"></div>
                    </button>
                </form>
            </div>
        </div>
    </nav>
    <div class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        <form method="post" action="{{ route('user.store') }}" class="form-horizontal">
                            @csrf
                            <div class="card-header card-header-text" data-background-color="rose">
                                <h4 class="card-title">Create User</h4>
                            </div>
                            <div class="card-content">
                                <div class="row">
                                    <label class="col-sm-2 label-on-left">NIK</label>
                                    <div class="col-sm-8">
                                        <div class="form-group label-floating is-empty">
                                            <label class="control-label"></label>
                                            <input type="text" class="form-control" placeholder="NIK" name="nik">
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <label class="col-sm-2 label-on-left">Name</label>
                                    <div class="col-sm-8">
                                        <div class="form-group label-floating is-empty">
                                            <label class="control-label"></label>
                                            <input type="text" class="form-control" placeholder="Name" name="name">
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <label class="col-sm-2 label-on-left">Email</label>
                                    <div class="col-sm-8">
                                        <div class="form-group label-floating is-empty">
                                            <label class="control-label"></label>
                                            <input type="email" class="form-control" placeholder="Email" name="email">
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <label class="col-sm-2 label-on-left">Password</label>
                                    <div class="col-sm-8">
                                        <div class="form-group label-floating is-empty">
                                            <label class="control-label"></label>
                                            <input type="password" class="form-control" placeholder="Password" name="password">
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <label class="col-sm-2 label-on-left">Phone Number</label>
                                    <div class="col-sm-8">
                                        <div class="form-group label-floating is-empty">
                                            <label class="control-label"></label>
                                            <input type="text" class="form-control" placeholder="Phone Number" name="phoneNumber">
                                        </div>
                                    </div>
                                </div>
                                <!-- <div class="row">
                                    <label class="col-sm-2 label-on-left">Quota</label>
                                    <div class="col-sm-8">
                                        <div class="form-group label-floating is-empty">
                                            <label class="control-label"></label>
                                            <input type="number" placeholder="Quota" class="form-control" name="quota">
                                        </div>
                                    </div>
                                </div> -->
                                <button type="submit" class="btn btn-fill btn-rose">Submit</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/users/index.blade.php
@extends('layouts.template')

@section('userMenu', 'active')

@section('content')
<div class="main-panel">
    <nav class="navbar navbar-transparent navbar-absolute">
        <div class="container-fluid">
            <div class="navbar-minimize">
                <button id="minimizeSidebar" class="btn btn-round btn-white btn-fill btn-just-icon">
                    <i class="material-icons visible-on-sidebar-regular">more_vert</i>
                    <i class="material-icons visible-on-sidebar-mini">view_list</i>
                </button>
            </div>
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#"> List Users </a>
            </div>
            <div class="collapse navbar-collapse">
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a href="#pablo" class="dropdown-toggle" data-toggle="dropdown">
                            <i class="material-icons">dashboard</i>
                            <p class="hidden-lg hidden-md">Dashboard</p>
                        </a>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            <i class="material-icons">notifications</i>
                            <span class="notification">5</span>
                            <p class="hidden-lg hidden-md">
                                Notifications
                                <b class="caret"></b>
                            </p>
                        </a>
                        <ul class="dropdown-menu">
                            <li>
                                <a href="#">Mike John responded to your email</a>
                            </li>
                            <li>
                                <a href="#">You have 5 new tasks</a>
                            </li>
                            <li>
                                <a href="#">You're now friend with Andrew</a>
                            </li>
                            <li>
                                <a href="#">Another Notification</a>
                            </li>
                            <li>
                                <a href="#">Another One</a>
                            </li>
                        </ul>
                    </li>
                    <li>
                        <a href="#pablo" class="dropdown-toggle" data-toggle="dropdown">
                            <i class="material-icons">person</i>
                            <p class="hidden-lg hidden-md">Profile</p>
                        </a>
                    </li>
                    <li class="separator hidden-lg hidden-md"></li>
                </ul>
                <form class="navbar-form navbar-right" role="search">
                    <div class="form-group form-search is-empty">
                        <input type="text" class="form-control" placeholder="Search">
                        <span class="material-input"></span>
                    </div>
                    <button type="submit" class="btn btn-white btn-round btn-just-icon">
                        <i class="material-icons">search</i>
                        <div class="ripple-container"></div>
                    </button>
                </form>
            </div>
        </div>
    </nav>
    <div class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-header card-header-icon" data-background-color="purple">
                            <i class="fa fa-clipboard"></i>
                        </div>
                        <div class="card-content">
                            <h4 class="card-title">List Users</h4>
                            <div class="toolbar">
                                <!--        Here you can write extra buttons/actions for the toolbar              -->
                            </div>
                            <div class="material-datatables">
                                <table class="datatables table table-striped table-no-bordered table-hover" cellspacing="0" width="100%" style="width:100%">
                                    <thead>
                                        <tr>
                                            <th>Nama</th>
                                            <th>Email</th>
                                            <th>Jenis Kelamin</th>
                                            <th>Telepon</th>
                                            <!-- <th>Vaksin dosis 1</th>
                                            <th>Vaksin dosis 2</th> -->
                                            <th class="disabled-sorting text-right">Actions</th>
                                        </tr>
                                    </thead>
                                    <tfoot>
                                        <tr>
                                            <th>Nama</th>
                                            <th>Email</th>
                                            <th>Jenis Kelamin</th>
                                            <th>Telepon</th>
                                            <!-- <th>Vaksin dosis 1</th>
                                            <th>Vaksin dosis 2</th> -->
                                            <th class="disabled-sorting text-right">Actions</th>
                                        </tr>
                                    </tfoot>
                                    <tbody>
                                        @forelse ($users as $user)
                                        <tr>
                                            <td>{{ $user['name'] }}</td>
                                            <td>{{ $user['email'] }}</td>
                                            <td>{{ $user['gender'] == 0 ? "Male" : "Female" }}</td>
                                            <td>{{ $user['phoneNumber'] }}</td>
                                            <td class="td-actions text-right">
                                                <a href="{{ route('test-covid.index', $user['uid'] ?? "") }}" type="button" rel="tooltip" class="btn btn-sm btn-success btn-round">
                                                    <i class="fa fa-medkit"></i>
                                                </a>
                                                <a href="{{ route('vaccine.show', $user['uid'] ?? "") }}" type="button" rel="tooltip" class="btn btn-sm btn-warning btn-round">
                                                    <i class="fa fa-crutch"></i>
                                                </a>
                                                <a href="{{ route('user.edit', $user['uid'] ?? "") }}" type="button" rel="tooltip" class="btn btn-sm btn-info btn-round">
                                                    <i class="material-icons">edit</i>
                                                </a>
                                                <!-- <a onclick="return confirm('Are you sure you want to delete this item?');" href="{{ route('user.destroy', $user['uid']) }}" rel="tooltip" class="btn btn-sm btn-danger btn-round">
                                                        <i class="material-icons">close</i>
                                                    </a> -->
                                            </td>
                                        </tr>
                                        @empty
                                        @endforelse
                                    </tbody>
                                </table>
                            </div>
                        </div>
                        <!-- end content-->
                    </div>
                    <!--  end card  -->
                </div>
                <!-- end col-md-12 -->
            </div>
            <!-- end row -->
        </div>
    </div>
    <!-- modal -->
    <div class="modal fade" id="modalVac" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLongTitle">Form Vaccine Cert</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <form method="#" action="#" id="form_vaccine_cert">
                    @csrf
                    <div class="modal-body">
                        <div class="form-group label-floating is-empty">
                            <label class="control-label">Vaccine Name</label>
                            <input type="text" class="form-control" name="vaccine_name" id="vaccine_name">
                            <span class="material-input"></span>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-primary" id="btn_save">Save changes</button>
                </form>
            </div>
        </div>
    </div>
</div>
</div>
@endsection

@section('script')
<script>
    let arr = []
    function update_vaccine(id, type, event) {
        if ($('#cbx_'+type).is(':checked')) {
            $('#modalVac').modal('show')
            
            arr.push(
                [
                    {
                        "name": "id",
                        "value": id
                    },
                    {
                        "name": "type",
                        "value": type
                    }
                ]
            )
        }
       /*  $(btn_save).click((e) => {
            e.preventDefault()
        }) */
        // window.location.href = `/vaccine-cert/${id}/${type}/update`;
    }

</script>
@endsection