routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'Auth\LoginController@showLoginForm');
Auth::routes(['register' => false]);

Route::group(['middleware'=>'isLoggedIn'], function() {
    Route::get('/dashboard', [
        'uses' => 'DashboardController@index',
        'as' => 'dashboard'
    ]);

    // route admin
    Route::group(['namespace'=>'Backend'], function() {
        Route::resource('place', 'PlaceController')->except(['destroy']);
        Route::get('/place/{id}/destroy', [
            'uses' => 'PlaceController@destroy',
            'as' => 'place.destroy'
        ]);

        Route::resource('user', 'UserController')->except(['destroy']);
        Route::get('/user/{id}/destroy', [
            'uses' => 'UserController@destroy',
            'as' => 'user.destroy'
        ]);

        Route::resource('satgas', 'SatgasController')->except(['destroy']);
        Route::get('/satgas/{id}/destroy', [
            'uses' => 'SatgasController@destroy',
            'as' => 'satgas.destroy'
        ]);

        Route::resource('vaccine', 'VaccineController')->except(['create', 'destroy', 'edit']);
        Route::get('/vaccine/{id}/create', [
            'uses' => 'VaccineController@create',
            'as' => 'vaccine.create'
        ]);
        Route::get('/vaccine/{uid}/{id}/edit', [
            'uses' => 'VaccineController@edit',
            'as' => 'vaccine.edit'
        ]);
        Route::get('/vaccine/{uid}/{id}/destroy', [
            'uses' => 'VaccineController@destroy',
            'as' => 'vaccine.destroy'
        ]);

        Route::resource('test-covid', 'TestCovidController')->except(['update', 'create', 'index', 'edit', 'destroy']);
        Route::group(['prefix'=>'test-covid','as'=>'test-covid.'], function() {
            Route::get('/test-covid/{uid}/index', [
                'uses' => 'TestCovidController@index',
                'as' => 'index'
            ]);
            Route::get('/test-covid/{uid}/create', [
                'uses' => 'TestCovidController@create',
                'as' => 'create'
            ]);
            Route::get('/test-covid/{uid}/{id}/edit', [
                'uses' => 'TestCovidController@edit',
                'as' => 'edit'
            ]);
            Route::put('/test-covid/{uid}/{id}/update', [
                'uses' => 'TestCovidController@update',
                'as' => 'update'
            ]);
            Route::get('/test-covid/{uid}/{id}/destroy', [
                'uses' => 'TestCovidController@destroy',
                'as' => 'destroy'
            ]);
        });

        Route::resource('user-journey', 'UserJourneyController');
        Route::group(['prefix' => 'user-journey', 'as' => 'user-journey.'], function() {
            Route::post('/get-journey', [
                'as' => 'get-journey',
                'uses' => 'UserJourneyController@getJourney'
            ]);
        });
        Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
    });

    // route satgas
    Route::group(['prefix' => 'dashboard-satgas', 'namespace'=>'Satgas', 'as' => 'satgas.'], function() {

        // test covid by satgas
        Route::get('/test-covid/datatable', [
            'as' => 'test-covid.datatable',
            'uses' => 'TestCovidController@datatable'
        ]);
        Route::get('/test-covid/{uid}/{id}/destroy', [
            'as' => 'test-covid.destroy',
            'uses' => 'TestCovidController@destroy'
        ]);
        Route::resource('test-covid', 'TestCovidController')->except(['show', 'edit', 'destroy']);

        Route::get('/vaccine/datatable', [
            'as' => 'vaccine.datatable',
            'uses' => 'VaccineController@datatable'
        ]);
        Route::get('/vaccine/{uid}/{id}/destroy', [
            'as' => 'vaccine.destroy',
            'uses' => 'VaccineController@destroy'
        ]);
        Route::resource('vaccine', 'VaccineController');
    });

    Route::get('get-user', [
        'as' => 'select.get-user',
        'uses' => 'SelectController@getUser'
    ]);
});

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav me-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ms-auto">
                        <!-- Authentication Links -->
                        @guest
                            @if (Route::has('login'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                                </li>
                            @endif

                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }}
                                </a>

                                <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/layouts/firebase.blade.php
<script>
      // For Firebase JS SDK v7.20.0 and later, measurementId is optional
    const firebaseConfig = {
        apiKey: "AIzaSyDEIZp8Y_4amWSfC2Wmi-I7T22ILvPsNqQ",
        authDomain: "covidtracker-2d006.firebaseapp.com",
        databaseURL: "https://covidtracker-2d006-default-rtdb.asia-southeast1.firebasedatabase.app",
        projectId: "covidtracker-2d006",
        storageBucket: "covidtracker-2d006.appspot.com",
        messagingSenderId: "707511474033",
        appId: "1:707511474033:web:c1a5869fe426ea16fb48d0",
        measurementId: "G-9Q4V03XJF4"
    };

    firebase.initializeApp(firebaseConfig);
</script>

resources/views/layouts/sidebar.blade.php
<div class="sidebar" data-active-color="purple">
    <div class="logo">
        <a href="#" class="simple-text">
            Backend Covid Tracker
        </a>
    </div>
    <div class="logo logo-mini">
        <a href="#" class="simple-text">
            Ct
        </a>
    </div>
    <div class="sidebar-wrapper">
        <div class="user">
            <div class="photo">
                <img src="/assets/img/faces/avatar.jpg" />
            </div>
            <div class="info">
                <a data-toggle="collapse" href="#collapseExample" class="collapsed">
                    Admin Covid Tracker
                    <b class="caret"></b>
                </a>
                <div class="collapse" id="collapseExample">
                    <ul class="nav">
                        <!-- <li>
                            <a href="#">My Profile</a>
                        </li>
                        <li>
                            <a href="#">Edit Profile</a>
                        </li> -->
                        <li>
                            <a class="dropdown-item" href="{{ route('logout') }}"
                                onclick="event.preventDefault();
                                                document.getElementById('logout-form').submit();">
                                {{ __('Logout') }}
                            </a>

                            <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                @csrf
                            </form>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <!-- Menu Admin -->
        @can('access-admin')
            <ul class="nav">
                <li class="@yield('dashboardMenu')" >
                    <a href="/dashboard">
                        <i class="material-icons">dashboard</i>
                        <p>Dashboard</p>
                    </a>
                </li>
                <li class="@yield('placeMenu')">
                    <a href="{{ route('place.index') }}">
                        <i class="material-icons">apartment</i>
                        <p>Places</p>
                    </a>
                </li>
                <li class="@yield('userMenu')">
                    <a href="{{ route('user.index') }}">
                        <i class="material-icons">person</i>
                        <p>Users</p>
                    </a>
                </li>
                <li class="@yield('satgasMenu')">
                    <a href="{{ route('satgas.index') }}">
                        <i class="material-icons">group</i>
                        <p>Satgas</p>
                    </a>
                </li>
                <li class="@yield('journeyMenu')">
                    <a href="{{ route('user-journey.index') }}">
                        <i class="material-icons">explore</i>
                        <p>User Journey</p>
                    </a>
                </li>
            </ul>
        @endcan

        @can('access-satgas')
            <ul class="nav">
                <li class="@yield('dashboardMenu')" >
                    <a href="/dashboard">
                        <i class="material-icons">dashboard</i>
                        <p>Dashboard</p>
                    </a>
                </li>
                <li class="@yield('TestCovidMenu')">
                    <a href="{{ route('satgas.test-covid.index') }}">
                        <i class="material-icons">group</i>
                        <p>Test Covid</p>
                    </a>
                </li>
                <li class="@yield('VaccineMenu')">
                    <a href="{{ route('satgas.vaccine.index') }}">
                        <i class="material-icons">group</i>
                        <p>Vaccine</p>
                    </a>
                </li>
            </ul>
        @endcan
    </div>
</div>

resources/views/layouts/template.blade.php
<!doctype html>
<html lang="en">


<!-- Mirrored from demos.creative-tim.com/material-dashboard-pro/examples/dashboard.html by HTTrack Website Copier/3.x [XR&CO'2014], Mon, 20 Mar 2017 21:29:18 GMT -->

<head>
    <meta charset="utf-8" />
    <link rel="apple-touch-icon" sizes="76x76" href="/assets/img/apple-icon.png" />
    <link rel="icon" type="image/png" href="/assets/img/favicon.png" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <title>Material Dashboard PRO by Creative Tim | Premium Bootstrap Admin Template</title>
    <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' name='viewport' />
    <meta name="viewport" content="width=device-width" />
    <!-- Canonical SEO -->
    <link rel="canonical" href="https://www.creative-tim.com/product/material-dashboard-pro" />
    <!--  Social tags      -->
    <meta name="keywords" content="material dashboard, bootstrap material admin, bootstrap material dashboard, material design admin, material design, creative tim, html dashboard, html css dashboard, web dashboard, freebie, free bootstrap dashboard, css3 dashboard, bootstrap admin, bootstrap dashboard, frontend, responsive bootstrap dashboard, premiu material design admin">
    <meta name="description" content="Material Dashboard PRO is a Premium Material Bootstrap Admin with a fresh, new design inspired by Google's Material Design.">
    <!-- Schema.org markup for Google+ -->
    <meta itemprop="name" content="Material Dashboard PRO by Creative Tim | Premium Bootstrap Admin Template">
    <meta itemprop="description" content="Material Dashboard PRO is a Premium Material Bootstrap Admin with a fresh, new design inspired by Google's Material Design.">
    <meta itemprop="image" content="https://.amazonaws.com/creativetim_bucket/products/51/opt_mdp_thumbnail.jpg">
    <!-- Twitter Card data -->
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:site" content="@creativetim">
    <meta name="twitter:title" content="Material Dashboard PRO by Creative Tim | Premium Bootstrap Admin Template">
    <meta name="twitter:description" content="Material Dashboard PRO is a Premium Material Bootstrap Admin with a fresh, new design inspired by Google's Material Design.">
    <meta name="twitter:creator" content="@creativetim">
    <meta name="twitter:image" content="https://.amazonaws.com/creativetim_bucket/products/51/opt_mdp_thumbnail.jpg">
    <!-- Open Graph data -->
    <meta property="fb:app_id" content="655968634437471">
    <meta property="og:title" content="Material Dashboard PRO by Creative Tim | Premium Bootstrap Admin Template" />
    <meta property="og:type" content="article" />
    <meta property="og:url" content="http://www.creative-tim.com/product/material-dashboard-pro" />
    <meta property="og:image" content="https://.amazonaws.com/creativetim_bucket/products/51/opt_mdp_thumbnail.jpg" />
    <meta property="og:description" content="Material Dashboard PRO is a Premium Material Bootstrap Admin with a fresh, new design inspired by Google's Material Design." />
    <meta property="og:site_name" content="Creative Tim" />
    <meta name="csrf-token" content="{{ csrf_token() }}" />

    <!-- Bootstrap core CSS     -->
    <link href="/assets/css/bootstrap.min.css" rel="stylesheet" />
    <!--  Material Dashboard CSS    -->
    <link href="/assets/css/material-dashboard.css" rel="stylesheet" />
    <!--  CSS for Demo Purpose, don't include it in your project     -->
    <link href="/assets/css/demo.css" rel="stylesheet" />
    <!--     Fonts and icons     -->
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Material+Icons" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/css/select2.min.css" integrity="sha512-nMNlpuaDPrqlEls3IX/Q56H36qvBASwb3ipuo3MxeWbsQB1881ox0cRv7UPTgBlriqoynt35KjEwgGUeUXIPnw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    @yield('css')
</head>

<body>
    @include('sweetalert::alert')
    <div class="wrapper">
        @include('layouts.sidebar')
        @yield('content')
    </div>
</body>
<!--   Core JS Files   -->
<script src="/assets/js/jquery-3.1.1.min.js" type="text/javascript"></script>
<script src="/assets/js/jquery-ui.min.js" type="text/javascript"></script>
<script src="/assets/js/bootstrap.min.js" type="text/javascript"></script>
<script src="/assets/js/material.min.js" type="text/javascript"></script>
<script src="/assets/js/perfect-scrollbar.jquery.min.js" type="text/javascript"></script>
<!-- Forms Validations Plugin -->
<script src="/assets/js/jquery.validate.min.js"></script>
<!--  Plugin for Date Time Picker and Full Calendar Plugin-->
<script src="/assets/js/moment.min.js"></script>
<script src="https://kit.fontawesome.com/a8221d5fda.js" crossorigin="anonymous"></script>
<!--  Charts Plugin -->
<!-- <script src="/assets/js/chartist.min.js"></script> -->
<!--  Plugin for the Wizard -->
<script src="/assets/js/jquery.bootstrap-wizard.js"></script>
<!--  Notifications Plugin    -->
<script src="/assets/js/bootstrap-notify.js"></script>
<!--   Sharrre Library    -->
<script src="/assets/js/jquery.sharrre.js"></script>
<!-- DateTimePicker Plugin -->
<script src="/assets/js/bootstrap-datetimepicker.js"></script>
<!-- Vector Map plugin -->
<script src="/assets/js/jquery-jvectormap.js"></script>
<!-- Sliders Plugin -->
<script src="/assets/js/nouislider.min.js"></script>
<!--  Google Maps Plugin    -->
<script src="https://maps.googleapis.com/maps/api/js"></script>
<!-- Select Plugin -->
<script src="/assets/js/jquery.select-bootstrap.js"></script>
<!--  DataTables.net Plugin    -->
<script src="/assets/js/jquery.datatables.js"></script>
<!-- Sweet Alert 2 plugin -->
<script src="/assets/js/sweetalert2.js"></script>
<!--	Plugin for Fileupload, full documentation here: http://www.jasny.net/bootstrap/javascript/#fileinput -->
<script src="/assets/js/jasny-bootstrap.min.js"></script>
<!--  Full Calendar Plugin    -->
<script src="/assets/js/fullcalendar.min.js"></script>
<!-- TagsInput Plugin -->
<script src="/assets/js/jquery.tagsinput.js"></script>
<!-- Material Dashboard javascript methods -->
<script src="/assets/js/material-dashboard.js"></script>
<!-- Material Dashboard DEMO methods, don't include it in your project! -->
<script src="/assets/js/demo.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/js/select2.min.js" integrity="sha512-2ImtlRlf2VVmiGZsjm9bEyhjGW4dU7B6TNwh/hx/iSByxNENtj3WVE6o/9Lj4TJeVXPi4bnOIMXFIJJAeufa0A==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<!-- firebase -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/firebase/8.2.1/firebase-app.min.js" integrity="sha512-Wt80kYLoTCwSaluT6Uhk6DAHV3NLXYWrdJSLmBtk1V9PRogftrA1/JD9ZYA++36bbZ3qV3vJAwBrvBJYqzhbLw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/firebase/8.2.1/firebase-database.min.js" integrity="sha512-OLWeyxC2NrpBDnJWw4q68nOiKe516C/4IrUI5mIvO4D3v+gT+8mblAacM1Ll5saxHAxw2SK/dyrXwOQ109l4mQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/firebase/8.2.1/firebase-firestore.min.js" integrity="sha512-PiY3aX3y9wFpvTNm8FfdhJWSeozJFyC8ObYBBMRRmFII/4gXZrwSdEpja5+zj1VHpc6/+z2z3mrguJPhrowwbA==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/firebase/8.2.1/firebase-analytics.min.js" integrity="sha512-I3Xtm9qS1nuJkElx7PUhXRWuV1+aPMRHtx3m3tsN93C4KQJcceSkCJjpiWytA0hTOkvjXayoYGl2tNCQX1nL1w==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>

<script src="{{ $cdn ?? asset('vendor/sweetalert/sweetalert.all.js')  }}"></script>
<script>
    $.ajaxSetup({
        headers: {
            'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
        }
    });
</script>

@yield('script')
<script type="text/javascript">
    $(document).ready(function() {

        // Javascript method's body can be found in assets/js/demos.js
        // demo.initDashboardPageCharts();


            $('.datatables').DataTable({
                "pagingType": "full_numbers",
                "lengthMenu": [
                    [10, 25, 50, -1],
                    [10, 25, 50, "All"]
                ],
                responsive: true,
                language: {
                    search: "_INPUT_",
                    searchPlaceholder: "Search records",
                }

            });

            $('.datepicker').datetimepicker({
                format: 'DD/MM/YYYY',
                icons: {
                    time: "fa fa-clock-o",
                    date: "fa fa-calendar",
                    up: "fa fa-chevron-up",
                    down: "fa fa-chevron-down",
                    previous: 'fa fa-chevron-left',
                    next: 'fa fa-chevron-right',
                    today: 'fa fa-screenshot',
                    clear: 'fa fa-trash',
                    close: 'fa fa-remove',
                    inline: true
                }
            });

    });
</script>


</html>